name: CI

on:
  push:
    branches: [ master, dev, feature/* ]
  pull_request:
    branches: [ master, dev, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://golang:1
      - uses: actions/checkout@v1
      - name: go test
        run: cd signal && go test -v ./...
